# The following is a bash function. Do not run as a standalone script. 

b64gzimport(){
	# Input is $1 and optionally $2, where $1 is a string generated by b64gz.sh and $2 is either 'evaluate' or 'print'(defaults to evaluate), to either execute the content of the string or print it to stdout
	if [[ "$2" == "evaluate" || ! -z $2]];then
		"$(echo "$1" | base64 -D | gzip -d)"
	elif [ "$2" == "print" ];then
		echo "$1" | base64 -D | gzip -d
	fi
}